components:
  schemas:
    ProductType:
      type: string
      enum:
        - product
        - bundle
        - subscriptionPlan
      x-enumNames:
        - Product
        - Bundle
        - SubscriptionPlan