type: object
description: Represents a product price
additionalProperties: false
properties:
  priceId:
    $ref: '../../../Common/Fields/ID.yml'
    description: Unique identifier for the product price entry
  productId:
    $ref: '../../../Common/Fields/ID.yml'
    description: Reference identifier for the related product
  priceKind:
    $ref: '../../../Common/Enums/PriceKind.yml#/components/schemas/PriceKind'
    description: The kind of the price (one-time or recurring)
  billingInterval:
    $ref: '../../../Common/Enums/BillingInterval.yml#/components/schemas/BillingInterval'
    description: The billing interval for recurring prices
    optional: true
  isActive:
    type: boolean
    description: Indicates whether the price is active
    example: true
    default: false
  amount:
    type: number
    format: decimal
    description: The amount of the price
  currencyCode:
    $ref: '../../../Common/Fields/CurrencyCode.yml'
    description: The currency code for the price