export enum SubscriptionErrors {
    SUBSCRIPTION_NOT_FOUND = 'SUBSCRIPTION_NOT_FOUND',
    CUSTOMER_NOT_FOUND = 'CUSTOMER_NOT_FOUND',
    PRICE_ID_NOT_FOUND = 'PRICE_ID_NOT_FOUND',
    INVOICE_NOT_PAID = 'INVOICE_NOT_PAID',
    UNEXPECTED_ERROR = 'UNEXPECTED_ERROR',
    WRONG_PAYMENT_FOR_SUBSCRIPTION = 'WRONG_PAYMENT_FOR_SUBSCRIPTION',
    NO_LINES_IN_EVENT = 'NO_LINES_IN_EVENT',
}