<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>VibraHeka.Domain</RootNamespace>
    <AssemblyName>VibraHeka.Domain</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BuilderPatternGenerator" />
    <PackageReference Include="BuilderPatternGenerator.Abstractions" />
    <PackageReference Include="CSharpFunctionalExtensions" />
    <PackageReference Include="MediatR" />
    <PackageReference Include="MediatR.Contracts" />
    <PackageReference Include="Riok.Mapperly" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Models\DTO\" />
    <Folder Include="Orders\Entities\" />
    <Folder Include="Orders\Models\" />
  </ItemGroup>

</Project>
