<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>VibraHeka.Domain</RootNamespace>
    <AssemblyName>VibraHeka.Domain</AssemblyName>
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
    <CompilerGeneratedFilesOutputPath>Generated</CompilerGeneratedFilesOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CSharpFunctionalExtensions" />
    <PackageReference Include="MediatR" />
    <PackageReference Include="MediatR.Contracts" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
    <PackageReference Include="NMoneys" />
    <PackageReference Include="Riok.Mapperly" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Users\Entities\" />
  </ItemGroup>

</Project>
