
variable ssm_namespace {
  default = "/VibraHeka/"
  description = "The SSM namespace for this environment"
}

variable prod_deployment {
  type = bool
  default = false
  description = "Whether we are performing a production deployment"
}

variable "stripe_event_bus_arn" {
  type = string
  description = "The ARN of the Stripe event bus"
}

variable "stripe_api_key" {
}

variable "password_reset_token_secret" {
  description = "Secret used by SendEmail lambda to build password reset tokens consumed by backend."
}

variable "password_reset_frontend_url" {
  description = "Frontend URL where users land to set a new password. Lambda appends token query param."
  default     = "http://localhost:5173/recover-password"
}

variable "password_reset_token_ttl_minutes" {
  description = "TTL in minutes for password reset tokens generated by SendEmail lambda."
  default     = 15
}
