
locals {
  context = {
    project_name = var.project_name
    workspace   = trim(replace(lower(terraform.workspace), "_", "-"), "-")
    resource_prefix = "${var.project_name}-${terraform.workspace}-"
    common_tags = {
      Project = var.project_name
      Environment = terraform.workspace
      dev = terraform.workspace != "prod" ? "true" : "false"
      ManagedBy = "Terraform"
    }
  }
  ssm_namespace = "/${var.project_name}/"
}

variable project_name {
  description = "The name of the project for this instance"
  type = string
  default = "VibraHeka"
}

variable ssm_namespace {
  default = "/VibraHeka/"
  description = "The SSM namespace for this environment"
}

variable prod_deployment {
  type = bool
  default = false
  description = "Whether we are performing a production deployment"
}

variable "stripe_event_bus_arn" {
  type = string
  description = "The ARN of the Stripe event bus"
}

variable "stripe_api_key" {
}

variable "password_reset_token_secret" {
  description = "Secret used by SendEmail lambda to build password reset tokens consumed by backend."
}

variable "password_reset_token_ttl_minutes" {
  description = "TTL in minutes for password reset tokens generated by SendEmail lambda."
  default     = 15
}

variable "ec2_enable_ssh_ingress" {
  description = "If true, opens inbound SSH (22) from ssh_allowed_cidrs. Prefer false and use SSM port forwarding instead."
  type        = bool
  default     = true
}

variable "ec2_existing_ssh_public_key" {
  description = "Optional existing SSH public key to use when create_ssh_key_pair is false."
  type        = string
  default     = ""
}

variable "ec2_allowed_ciders" {
  description = "CIDR ranges allowed to connect via SSH to the EC2 instance."
  type        = list(string)
  default     = ["0.0.0.0/0"]
}

variable "ec2_backend_port" {
  description = "Port where the backend process listens inside EC2."
  type        = number
  default     = 8080
}

variable "ec2_instance_type" {
  description = "EC2 instance type for the backend host (spot)."
  type        = string
  default     = "t4g.nano"
}

variable "private_subnet_a_cidr" {
  description = "CIDR block for private subnet A."
  type        = string
  default     = "10.60.1.0/24"
}

variable "vpc_cidr" {
  description = "CIDR block for the private VPC hosting backend resources."
  type        = string
  default     = "10.60.0.0/16"
}


