using System.ComponentModel;
using FluentValidation.Results;
using FluentValidation.TestHelper;
using NUnit.Framework;
using VibraHeka.Application.Recordings.Queries.GetRecordingDownloadUrl;
using VibraHeka.Domain.Recordings.Errors;

namespace VibraHeka.Application.UnitTests.Catalog.Queries.GetRecordingDownloadUrl;

[TestFixture]
[NUnit.Framework.Category("Unit")]
public sealed class GetRecordingDownloadUrlQueryValidatorTest : GenericGetRecordingDownloadUrlTest
{
    private GetRecordingDownloadUrlQueryValidator RealValidator = default!;

    [SetUp]
    public override void SetUp()
    {
        base.SetUp();
        RealValidator = new GetRecordingDownloadUrlQueryValidator();
    }

    #region Empty / Whitespace RecordingId Tests

    [TestCase("", TestName = "Empty string")]
    [TestCase("   ", TestName = "Whitespace only")]
    [DisplayName("Should fail validation when RecordingId is empty or whitespace")]
    public void ShouldFailValidationWhenRecordingIdIsEmptyOrWhitespace(string recordingId)
    {
        // Given: a query with an empty or whitespace recording ID
        GetRecordingDownloadUrlQuery query = BuildValidQuery(recordingId);

        // When: validating the query
        TestValidationResult<GetRecordingDownloadUrlQuery> result = RealValidator.TestValidate(query);

        // Then: should have a validation error for RecordingId with InvalidRecordingId error code
        result.ShouldHaveValidationErrorFor(x => x.RecordingId)
            .WithErrorMessage(RecordingErrors.InvalidRecordingId);
    }

    #endregion

    #region Invalid GUID Format Tests

    [TestCase("not-a-guid", TestName = "Non-GUID string")]
    [TestCase("12345", TestName = "Numeric string")]
    [TestCase("abc-def-ghi-jkl", TestName = "Hyphenated non-GUID string")]
    [DisplayName("Should fail validation when RecordingId is not a valid GUID format")]
    public void ShouldFailValidationWhenRecordingIdIsNotValidGuid(string recordingId)
    {
        // Given: a query with an invalid (non-GUID format) recording ID
        GetRecordingDownloadUrlQuery query = BuildValidQuery(recordingId);

        // When: validating the query
        TestValidationResult<GetRecordingDownloadUrlQuery> result = RealValidator.TestValidate(query);

        // Then: should have a validation error for RecordingId with InvalidRecordingId error code
        result.ShouldHaveValidationErrorFor(x => x.RecordingId)
            .WithErrorMessage(RecordingErrors.InvalidRecordingId);
    }

    #endregion

    #region Happy Path Tests

    [Test]
    [DisplayName("Should pass validation when RecordingId is a valid GUID string")]
    public void ShouldPassValidationWhenRecordingIdIsValidGuid()
    {
        // Given: a query with a valid GUID recording ID
        GetRecordingDownloadUrlQuery query = BuildValidQuery(Guid.NewGuid().ToString());

        // When: validating the query
        TestValidationResult<GetRecordingDownloadUrlQuery> result = RealValidator.TestValidate(query);

        // Then: should not have any validation error for RecordingId
        result.ShouldNotHaveValidationErrorFor(x => x.RecordingId);
    }

    [Test]
    [DisplayName("Should pass validation when all fields are valid")]
    public void ShouldPassValidationWhenAllFieldsAreValid()
    {
        // Given: a query with all fields valid (generated by BuildValidQuery)
        GetRecordingDownloadUrlQuery query = BuildValidQuery();

        // When: validating the query
        TestValidationResult<GetRecordingDownloadUrlQuery> result = RealValidator.TestValidate(query);

        // Then: should not have any validation errors
        result.ShouldNotHaveAnyValidationErrors();
    }

    #endregion

    #region CascadeMode Tests

    [Test]
    [DisplayName("Should report exactly one error per field when CascadeMode is Stop")]
    public void ShouldReportExactlyOneErrorForRecordingIdWhenCascadeModeIsStop()
    {
        // Given: a query with an empty recording ID (triggers both NotEmpty and Must rules)
        GetRecordingDownloadUrlQuery query = BuildValidQuery("");

        // When: validating the query
        TestValidationResult<GetRecordingDownloadUrlQuery> result = RealValidator.TestValidate(query);

        // Then: should have exactly 1 error for RecordingId (CascadeMode.Stop stops after first failure)
        IEnumerable<ValidationFailure> idErrors = result.Errors
            .Where(e => e.PropertyName == nameof(GetRecordingDownloadUrlQuery.RecordingId))
            .ToList();

        Assert.That(idErrors.Count(), Is.EqualTo(1),
            $"Expected exactly 1 error for RecordingId with CascadeMode.Stop, but got {idErrors.Count()}");
        Assert.That(idErrors.First().ErrorMessage, Is.EqualTo(RecordingErrors.InvalidRecordingId),
            $"Expected error '{RecordingErrors.InvalidRecordingId}' but got: '{idErrors.First().ErrorMessage}'");
    }

    #endregion
}


