import {createCipheriv, createHash, randomBytes, randomUUID} from "crypto";
import IPasswordResetTokenService from "@Domain/Interfaces/IPasswordResetTokenService";
import {PasswordResetTokenPayload} from "@Domain/Entities/PasswordResetTokenPayload";
import {err, ok, Result} from "neverthrow";
import EmailSenderErrors from "@Domain/Errors/EmailSenderErrors";

const TOKEN_PREFIX = "v1";
const NONCE_BYTES = 12;
const TAG_BYTES = 16;

/**
 * Creates proprietary password-reset tokens consumed by backend replay-protection flow.
 */
export default class PasswordResetTokenService implements IPasswordResetTokenService {
    private readonly encryptionKey: Buffer;
    private readonly secretFingerprint: string;

    constructor(
        tokenSecret: string,
        private readonly frontendResetUrl: string,
        private readonly tokenTtlMinutes: number
    ) {
        const normalizedSecret = tokenSecret.trim();
        this.encryptionKey = createHash("sha256")
            .update(normalizedSecret, "utf-8")
            .digest();
        this.secretFingerprint = this.encryptionKey.toString("hex").slice(0, 12);
        console.log("Password reset token service initialized", {
            secretFingerprint: this.secretFingerprint
        });
    }

    /**
     * Builds an encrypted token payload for reset confirmation.
     *
     * @param email User email.
     * @param cognitoCode Plain Cognito forgot-password code.
     * @returns Result with encoded token or domain error.
     */
    public BuildPasswordResetToken(email: string, cognitoCode: string): Result<string, EmailSenderErrors> {
        try {
            console.log("Building password reset token payload", {email});
            const expiresAtUnix = Math.floor(Date.now() / 1000) + this.tokenTtlMinutes * 60;
            const payload: PasswordResetTokenPayload = {
                Email: email,
                CognitoCode: cognitoCode,
                TokenId: randomUUID(),
                ExpiresAtUnix: expiresAtUnix
            };

            const plainBytes = Buffer.from(JSON.stringify(payload), "utf-8");
            const nonce = randomBytes(NONCE_BYTES);
            const cipher = createCipheriv("aes-256-gcm", this.encryptionKey, nonce, {authTagLength: TAG_BYTES});
            const encrypted = Buffer.concat([cipher.update(plainBytes), cipher.final()]);
            const tag = cipher.getAuthTag();
            const payloadBytes = Buffer.concat([nonce, tag, encrypted]);
            const encoded = payloadBytes.toString("base64url");
            return ok(`${TOKEN_PREFIX}.${encoded}`);
        } catch (error) {
            console.error("Failed building password reset token", {email, error});
            return err(EmailSenderErrors.TOKEN_BUILD_FAILED);
        }
    }

    /**
     * Builds the final reset link used by frontend.
     *
     * @param token Proprietary token generated by this service.
     * @returns Result with final link or domain error.
     */
    public BuildPasswordResetLink(token: string): Result<string, EmailSenderErrors> {
        if (!this.frontendResetUrl || this.frontendResetUrl.trim().length === 0) {
            console.log("Frontend reset URL not configured, returning token as fallback payload");
            return ok(token);
        }

        try {
            const separator = this.frontendResetUrl.includes("?") ? "&" : "?";
            return ok(`${this.frontendResetUrl}${separator}token=${encodeURIComponent(token)}`);
        } catch (error) {
            console.error("Failed building password reset link", {error});
            return err(EmailSenderErrors.TOKEN_BUILD_FAILED);
        }
    }
}
