<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Zoom\" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="ZoomNet" />
    </ItemGroup>

</Project>
