<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <RootNamespace>VibraHeka.Web</RootNamespace>
    <AssemblyName>VibraHeka.Web</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Application\Application.csproj" />
    <ProjectReference Include="..\Infrastructure.Persistence\Infrastructure.Persistence.csproj" />
    <ProjectReference Include="..\Infrastructure.Rest.Client\Infrastructure.Rest.Client.csproj" />
    <ProjectReference Include="..\Infrastructure\Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CSharpFunctionalExtensions" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="NSwag.AspNetCore" />
    <PackageReference Include="NSwag.CodeGeneration.CSharp" />
    <PackageReference Include="NSwag.MSBuild">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Riok.Mapperly" />
    <PackageReference Include="Serilog" />
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="Serilog.Enrichers.Environment" />
    <PackageReference Include="Serilog.Sinks.AwsCloudWatch" />
    <PackageReference Include="Serilog.Sinks.Console" />
  </ItemGroup>

  <ItemGroup>
    <_ContentIncludedByDefault Remove="wwwroot\api\specification.json" />
    <_ContentIncludedByDefault Remove="artifacts\tmpbuild\debug\appsettings.Development.json" />
    <_ContentIncludedByDefault Remove="artifacts\tmpbuild\debug\appsettings.json" />
    <_ContentIncludedByDefault Remove="artifacts\tmpbuild\debug\appsettings.Test.json" />
    <_ContentIncludedByDefault Remove="artifacts\tmpbuild\debug\ClientApp\package-lock.json" />
    <_ContentIncludedByDefault Remove="artifacts\tmpbuild\debug\VibraHeka.Web.deps.json" />
    <_ContentIncludedByDefault Remove="artifacts\tmpbuild\debug\VibraHeka.Web.runtimeconfig.json" />
    <_ContentIncludedByDefault Remove="artifacts\tmpbuild\debug\VibraHeka.Web.staticwebassets.endpoints.json" />
    <_ContentIncludedByDefault Remove="artifacts\tmpbuild\debug\VibraHeka.Web.staticwebassets.runtime.json" />
  </ItemGroup>

  <ItemGroup>
    <NSwagConfigs Include="$(ProjectDir)Contracts\**\*.nswag" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Generated\" />
  </ItemGroup>
  

  <!-- Auto-generated Open API specification and Angular TypeScript clients -->
  <PropertyGroup>
    <RunPostBuildEvent>OnBuildSuccess</RunPostBuildEvent>
  </PropertyGroup>

  <Target Name="CleanGeneratedOpenApi" BeforeTargets="GenerateOpenApiControllers">
    <RemoveDir Directories="$(ProjectDir)Generated" />
  </Target>
  
  <Target Name="GenerateOpenApiClients" BeforeTargets="CoreCompile">

    <Message
      Importance="High"
      Text="NSwag configs found: @(NSwagConfigs)"
    />

    <Exec
      ConsoleToMSBuild="true"
      ContinueOnError="true"
      Command="$(NSwagExe_Net100) run &quot;%(NSwagConfigs.FullPath)&quot; /variables:Configuration=$(Configuration)"
      WorkingDirectory="$(ProjectDir)" />
    <Message Text="Generated OpenAPI clients for %(NSwagConfigs.Identity)" Importance="high" />
    <ItemGroup>
      <Compile Include="$(ProjectDir)Generated\**\*.cs" Exclude="@(Compile)"/>
    </ItemGroup>
  </Target>
  
  <Target Name="NSwag" AfterTargets="PostBuildEvent" Condition=" '$(Configuration)' == 'Debug' And '$(SkipNSwag)' != 'True' ">
    <Exec ConsoleToMSBuild="true" ContinueOnError="true"  EnvironmentVariables="ASPNETCORE_ENVIRONMENT=Development" Command="$(NSwagExe_Net100) run config.nswag /variables:Configuration=$(Configuration)">
      <Output TaskParameter="ExitCode" PropertyName="NSwagExitCode" />
      <Output TaskParameter="ConsoleOutput" PropertyName="NSwagOutput" />
    </Exec>

    <Message Text="$(NSwagOutput)" Condition="'$(NSwagExitCode)' == '0'" Importance="low" />
    <Error Text="$(NSwagOutput)" Condition="'$(NSwagExitCode)' != '0'" />
  </Target>
</Project>
